### ISSUE TITLE
sidebar avatar, 회원이름 UI 및 링크 구현

### ISSUE THREAD

**Issue by d36choi** [d36choi/hfrecruit-backend#16]
![image](https://user-images.githubusercontent.com/40600306/91627641-a56e1080-e9f3-11ea-8fd6-9aed0f5cece5.png)

![image](https://user-images.githubusercontent.com/40600306/91627678-ecf49c80-e9f3-11ea-8d8c-54e1b75d8ab5.png)

 **template/ sidebar.mustache 에 구현해주세요.**

**추가적인 css 가 필요하다면 header.mustache에, 추가적인 .js파일이 필요하다면 footer.mustache 에 적어주시면 알아서 적용 됩니다.**

### header.mustache의 예시
```
<link rel="stylesheet" href="css/sidebar.css">
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
```
### footer.mustache 의 예시
```
script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<!-- /#wrapper -->
<!-- Menu Toggle Script -->
<!--아래 스크립트 적용을 위해서는 id가 wrapper 인 div 안에 모두 감싸야 합니다. -->
<script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
</script>
```

사이드바는 모든 페이지에 필요하므로 코드의 생산성을 위해 template/ 에 따로 파일화했습니다.
ppt UI 에는 mypage 로 이동하는 메뉴가 따로 없습니다. 위 사진의 이름이나 아바타 아이콘을 클릭하면
마이페이지로 연결될 수 있게 하죠~

**Comment by dusdn1702** [comment]
구현 완료!🙌

**Comment by d36choi** [comment]
토글 기능까지 구현하셧다니.. :+1:

![image](https://user-images.githubusercontent.com/40600306/91652808-85168280-ead5-11ea-9918-a546106b8747.png)

![image](https://user-images.githubusercontent.com/40600306/91652809-8c3d9080-ead5-11ea-8adf-c9ba4a405152.png)

그런데 돌려보니 toggle 버튼이 아래로 가네요. 
그리고 이 토글버튼이 사실 저 메뉴들을 열고 닫는 게 아니라 사이드바 자체를 열고 닫는걸로
저는 생각했거든요. 이 버튼처럼요. @dusdn1702 
![image](https://user-images.githubusercontent.com/40600306/91652840-c73fc400-ead5-11ea-90b9-6514ee5124bc.png)

**Comment by dusdn1702** [comment]
흠 사이드바를 열고 닫는 토글이라면  마이페이지 자체에 구현되어야 다시 열 수 있을 것 같아요!!
그렇게 되면 토글 메뉴가 꼭 필요한지 의문이어서용,,
저는 마이페이지에서 볼 수 있는 것들이 어차피 전부 링크를 타고 가기에 토글메뉴 바로 간단히 갈 수 있도록 만들었는데 이 부분에 대해서는 다같이 한번 생각해보는게 좋을 것 같아요~!~!

**Comment by d36choi** [comment]
전체 사이드바 토글이 연우님 말대로 없어도 될 거 같긴 해요 (ppt UI에는 그렇게 만들어놓긴 했는데) 서브 메뉴를 만들거면 토글로 하는것보다 마이페이지에 들어가면 서브메뉴가 다 열려있게 하는것도 좋을 거 같아요.
월욜날 얘기해봐요~ 몇시더라
