### ISSUE TITLE
채용공고 등록(회사) 페이지 UI 구현

### ISSUE THREAD

**Issue by d36choi** [d36choi/hfrecruit-backend#29]
![image](https://user-images.githubusercontent.com/40600306/91868545-ccf10180-ecaf-11ea-92cb-7df211a0f3ab.png)

이 앞에 회사소개라던가,, 일정공지라던가 이런거 쓰는 칸들이 다 있어야될거같네요.
UI엔 없던데 채용공고 테이블에  있는 항목들을 다 쓸수있게끔 만듭시다

**Comment by dusdn1702** [comment]
![image](https://user-images.githubusercontent.com/43775108/91961895-c792c600-ed46-11ea-8878-122c0d67ef91.png)
