### ISSUE TITLE
package import 오류

### ISSUE THREAD

**Issue by dusdn1702** [d36choi/hfrecruit-backend#38]
import com.hanium.hfrecruit.domain.recruit.Recruit;
=>
import com.hanium.hfrecruit.domain.Recruit.Recruit;
으로 전부 수정!

**Comment by d36choi** [comment]
![image](https://user-images.githubusercontent.com/40600306/92010107-57a33080-ed84-11ea-95d8-cfd1fb7448e1.png)

패키지명은 소문자가 맞지않나요??
