### ISSUE TITLE
oauth로그인 후 유저 추가정보 입력받아서 db에 저장하기

### ISSUE THREAD

**Issue by wookyoungkim** [d36choi/hfrecruit-backend#44]

**Comment by wookyoungkim** [comment]
<img width="903" alt="스크린샷 2020-09-06 오전 5 37 40" src="https://user-images.githubusercontent.com/49271553/92313145-2d12db00-f003-11ea-8353-cac75983c9b7.png">
 눈물 나는 성공, , ,

**Comment by wookyoungkim** [comment]
이미 가입된 회원에 대한 처리는 추후에 ,,

**Comment by d36choi** [comment]
👍
