### ISSUE TITLE
백엔드 entity class 들 만들기

### ISSUE THREAD

**Issue by d36choi** [d36choi/hfrecruit-backend#6]
db에 정의 되어있는 테이블별로 매칭이 되는 jpa entity class 를 만듭니다.

**Comment by wookyoungkim** [comment]
<img width="1440" alt="스크린샷 2020-08-29 오전 3 50 01" src="https://user-images.githubusercontent.com/49271553/91605042-c52d1680-e9aa-11ea-8673-f0530e1bab1c.png">

workbench reverse engineering tool로 프로젝트 런시 설계한 erd대로 테이블 생성됨을 확인 !

**Comment by d36choi** [comment]
👍  머지해주세여
